### ISSUE TITLE
Parts of this could be redistributed earlier into Rails

### ISSUE THREAD

**Issue by authorbeard** [learn-co-curriculum/rails-forms-readme#6]
The section where it distinguishes the two--especially the separation of the router and controller--would be helpful earlier on in the Rails section. It's easy enough to figure out from the diagram there, but simply spelling it out like this would clarify what "actions" mean here. In fact, doing smaller versions of the ActiveRecord unit for ActionPack and FormBuilder would help clarify just how the magic isn't really magic. Another example is Nokogiri, where it was explained that scrapers using that return specific types of objects known as Nokogiri objects that can be dealt with in certain ways. 

Last note: the way params can be nested in forms wasn't actually clear to me earlier on, when symbols were being used. The author had referred to this ability, but I wasted some time trying this out before just working around it, and a couple steps before realizing that the update and create methods used here spelled out the steps more than the ones I thought we should be using (#create instead of #new then #save, for example).

**Comment by pletcher** [comment]
I'm guessing that you're referencing, at least in part, [this lab](https://github.com/learn-co-curriculum/sinatra-routes-readme)? I'm having a hard time following the first paragraph. How can we make routing/controller actions clearer?

As for the final note, I wouldn't consider that a waste of time at all. That kind of exploring is the best way to learn -- ultimately, it's what Learn.co's lessons try to achieve for students (and is deliberately a part of how they work).

**Comment by authorbeard** [comment]
Charles, 

Thanks for responding. Been stuck in JS a couple days and barely looking at my email. My only real point was that the separation of routing from controllers was a huge point of difference with Sinatra; by now, I can't remember exactly which part gave me trouble, but that's because I wound up spending so much time raking/setting routes and defining/ordering controller actions that now I get it. Ish.

The rest is FWIW: 

I often avoid writing these because of this specific issue; I wanted to give some feedback in this case (and genuinely sorry if this ain't the right channel for it) because a sentence or two at the beginning of rails that pointed out the importance of routing (or even beginning it with something culled from [this](http://guides.rubyonrails.org/routing.html) ) would have framed all the rest of it and made it much easier to grasp. That's what I meant by wasted time--I usually benefit from any amount of googling around for answers--but there are times when that whole process (specifically filtering out all the erroneous/suboptimal/out-of-date information) takes a lot longer than it's really worth. So I was writing out of frustration, which isn't a great idea, but trying to avoid sounding at all as nasty as some of the GH issue exchanges I've seen (esp. when I was hunting down a Nokogiri issue). I decided to bring it up because I think adding a sentence or two early on ("Remember how a controller looks in Sinatra? Well, in Rails, it's now separated into this file here and this other file over here") could avoid this and it wouldn't be costing anybody any really crucial discoveries. There's plenty of stuff we have to figure out on our own later on that deserves to be left that way. Anyway, I've heard a couple times that, as one of the earlier students through the curriculum, I should try to give feedback where I can. So that's another reason I wrote. 

As for the rest of it, it was just getting tripped up on some of the changes to the style in this section; I've gotten more comfortable pushing on through a unit then looping back as need be; the stubs used as examples tripped me up a bit. 

Sorry it was unclear and overlong, but I do appreciate you getting back to me.

**Comment by pletcher** [comment]
@authorbeard Thanks for the detailed response! I think you're right -- some comparisons between the two frameworks to start would be super helpful. I'm going to reopen this issue and close it when I find a good place to put that.

(Routing in Rails is super weird. As someone who has done a lot of Rails but not necessarily willingly, The Rails Way™ of routing is a bit odd. Treating routes as "mere" configuration is strange, the rules about what will and won't work require learning a lot of conventions, and the opacity of the router itself is the source of limitless confusion.)
