### ISSUE TITLE
Routes section at end of README does not appear to belong...

### ISSUE THREAD

**Issue by tracypholmes** [learn-co-curriculum/rails-forms-readme#9]
The lesson is about forms. However, at the very end, there is a blurb related to `routes.rb` that does not mesh with the rest of the lesson at all. Current verbiage is 
>RESOURCES IN ROUTES.RB
Probably the biggest difference between Sinatra and Rails
In Sinatra, in app.rb you had blocks that corresponded to each path (fusing the router and the controller together)
In Rails, you have this routes.rb convention that separates the routes from the controllers
Via the resources parameter, Rails metaprograms several routes for you that correspond to specific actions (GET, POST, PATCH)

**Comment by curiositypaths** [comment]
Hi @tracypholmes 

Thank you for bringing this to our attention. We removed the out of context routes section.

As always thank you for contributing!
